apiVersion: v1
kind: Service
metadata:
  name: backend-java
  namespace: apps
spec:
  selector:
    app: backend-java
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
