apiVersion: v1
kind: Service
metadata:
  # Ejercicio 5:
  # StatefulSet necesita un serviceName estable.
  name: backend-java-headless
  namespace: apps
spec:
  clusterIP: None
  selector:
    app: backend-java
  ports:
    - name: http
      port: 8080
      targetPort: 8080
