apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-python
  namespace: argocd
spec:
  project: training-project
  source:
    repoURL: https://github.com/rngamon-alt/project-skeleton.git
    targetRevision: HEAD
    # TODO ejercicio 3:
    # Ajustar al path exacto del componente Python.
    path: k8s/04-apps/backend-python
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
