apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddl-job
  namespace: argocd
spec:
  project: training-project
  source:
    repoURL: https://github.com/rngamon-alt/project-skeleton.git
    targetRevision: HEAD
    # TODO ejercicio 3:
    # Revisar si quieres separar ConfigMap y Job o tratarlos juntos.
    path: k8s/03-jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
