apiVersion: v1
kind: Service
metadata:
  name: backend-python
  namespace: apps
spec:
  selector:
    app: backend-python
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
